### ISSUE TITLE
Proxy Yes/No not saving

### ISSUE THREAD

**Issue by Dh42** [thirtybees/piwikanalyticsjs#1]
The proxy yes/no is not saving the state, also the proxy url is not saving.

**Comment by romaric33** [comment]
The Yes/No switch for proxy script saves only if you use the Save button from its own options block, that's to say the first Save button following the Yes/No switch.

**Comment by firstred** [comment]
Thanks for the extra info. It's fixed by ajaxing it all: https://github.com/thirtybees/piwikanalyticsjs/commit/9e7ece1fa260b7099368cd620fe81efebc0085b9
