### ISSUE TITLE
PHP 7.1 and 7.2 compatibility 

### ISSUE THREAD

**Issue by Dh42** [thirtybees/piwikanalyticsjs#2]
Needs to be made compatible with these versions.

**Comment by DaoKakao** [comment]
I added following code between lines #456 and 457: self::$errors = [];
So, the error has gone away.
I'm not sure, but there's another lines of code having same assignment. Should it be fixed also?

**Comment by firstred** [comment]
Yeah and more.
`static::$errors = [];`
and `static::$error = '';`
are better.

**Comment by firstred** [comment]
Taken care of with v1.2.0.
