### ISSUE TITLE
( ) in _paq.push causes JS errors

### ISSUE THREAD

**Issue by romaric33** [thirtybees/piwikanalyticsjs#3]
On the cart/checkout page, JS handles ( ) characters wrongly in **_paq.push** and the JS fails, which in turn can break page loading.
These ( ) are added when product has attributes.

Example error
============
SyntaxError: missing ] after element list at line 1529 column 141
Note: [ opened at line 1529, column 66

Lines with the error
===============
`                                                        _paq.push(['addEcommerceItem', '16#105', 'Tenue Petit Kiki salopette soleil (Boîte d'origine : absente)', ["Tenues"], '22', '1']);
                            _paq.push(['addEcommerceItem', '133#100', 'Mini Kiki Le Vrai 8 cm (Variante : Avec tétine)', ["Kiki marron"], '18', '1']);`

**Comment by firstred** [comment]
Seems like the `'` in `Boîte d'or` is not being escaped. Let's have a look where that comes from.

**Comment by firstred** [comment]
JS console shows the error:
![paqpush](https://user-images.githubusercontent.com/6775736/36262983-484e2f34-1269-11e8-8286-c81114a29b71.png)

**Comment by romaric33** [comment]
You are probably right. The attribute name contains ' and I don't know where in the code it should but doesn't escape this character.

**Comment by firstred** [comment]
This change should fix it: https://github.com/thirtybees/piwikanalyticsjs/commit/6862b5213415fd0640962e990c35c737123ac979

**Comment by romaric33** [comment]
Does fix my issue. Thanks a lot 👍

**Comment by firstred** [comment]
Nice :D 

Thanks for letting us know.

**Comment by romaric33** [comment]
I have found a new issue which seems related.

The console shows the error in the JS:
 _paq.push is said to contain an illegal character in this line column 227:
`                                _paq.push(['addEcommerceItem', '175#30', 'Peluche Kiki marron 19 cm (Yeux : bleus, Pieds : avec marque \"Kiki le vrai\" à gauche (à partir du milieu des années 1980), Etiquette : non précisé)', **[**\"Accueil\",\"Kiki marron\"], '23', '1']);`

The first [ in [\"Accueil\",\"Kiki marron\"] is the illegal character.

**Comment by romaric33** [comment]
The same issue appeared on 
`_paq.push(['setEcommerceView`

You seem to have added **escape javascript** to a lot of variables which may not to need it.

**Comment by romaric33** [comment]
Piwik instance doesn't seem to receive any statistics anymore. I think it was wrong to javascript escape {$PIWIK_HOST} and probably other variables.

I have restored previous version of the two modified templates.
Then I only added javascript escaping to the two uses of {$_product.NAME} in jstracking.tpl 
Issue with _paq.push(['addEcommerceItem is solved.
Piwik instance receives statistics again.

Before adding javascript escaping to other variables, I believe it would be better to double check if it's useful and safe. Not being a developer, I can only say that as an idea.

**Comment by romaric33** [comment]
On the other hand, maybe it was useful to replace some escape:'htmlall':'UTF-8' with javascript escaping on category names, product names, etc. because it converts characters in an easy to read manner.

For example ' becomes      & # 039 ;     in html 
but it becomes     \ '     in javascript which is better for Piwik stats readability.

**Comment by romaric33** [comment]
I'm back commenting on my own thread... Hope it can be of some use to someone because not being a developer, I am not very good at doing that kind of stuff.

Finally, turns out the issue is on Cloudways side: HTTP_X_FORWARDED_FOR returns both the visitor's IP and 127.0.0.1 for some reason. Module's front controller piwik.php has a private function, getVisitIp(), that is unable to handle that 2 IPs correctly.

**Original function**
`    private function getVisitIp() {
        $matchIp = '/^([0-9]{1,3}\.){3}[0-9]{1,3}$/';
        $ipKeys = array(
            'HTTP_X_FORWARDED_FOR',
            'HTTP_CLIENT_IP',
            'HTTP_CF_CONNECTING_IP',
        );
        foreach ($ipKeys as $ipKey) {
            if (isset($_SERVER[$ipKey]) && preg_match($matchIp, $_SERVER[$ipKey])) {
                return $_SERVER[$ipKey];
            }
        }
        return $this->arrayValue($_SERVER, 'REMOTE_ADDR');
    }`

For my own use I have replaced the getVisitIp() function with that code which is suitable for my environment and might be good for other Cloudways users. 

**New function**
`    private function getVisitIp() {
        $xffaddrs = explode(',',$_SERVER['HTTP_X_FORWARDED_FOR']);
        $visitorrealip = $xffaddrs[0];
        return $visitorrealip;
        return $this->arrayValue($_SERVER, 'REMOTE_ADDR');
    }`

Now Piwik always gets the visitor's real IP and reports it well on the analytics dashboard.

**Comment by firstred** [comment]
Taken care of with v1.2.0.
