### ISSUE TITLE
Visitor's IP is 127.0.0.1 when Piwik (Matomo) instance runs on a Cloudways server

### ISSUE THREAD

**Issue by romaric33** [thirtybees/piwikanalyticsjs#5]
I am using TB 1.0.3 and ThirtyBees’ Piwik module on Cloudways. Piwik is a self hosted instance on Cloudways too.

Cloudways has Varnish which acts as a proxy and has to be configured in order to get user’s real IP instead of server’s self IP (127.0.0.1).
See: https://matomo.org/faq/how-to-install/faq_98/
These settings are correctly set on my Piwik instance.

The issue:

When the visitor isn’t logged in on the TB shop, his IP is correctly reported in Piwik.
Once the visitor logs in, his IP becomes 127.0.0.1 in Piwik.

**Comment by romaric33** [comment]
This issue may not be confirmed finally.
Non logged in users are now reported with 127.0.0.1 IP too.

This is more a server configuration related issue, with Varnish or something else on Cloudways. May be sort this out with Piwik team and Cloudways support as it seems not to be caused by the module.

**Comment by romaric33** [comment]
I have kept investigating and the issue is not related to the module. I am replying here if it can help other people.

When using Cloudways with Varnish, HTTP_X_FORWARDED_FOR returns two IPs: the visitor's real IP and 127.0.0.1. Piwik gets confused: it seems to use one then the other.

The solution for Wordpress is to explode HTTP_X_FORWARDED_FOR and keep only the first one which is the right one: https://www.gulshankumar.net/fix-wordpress-showing-localhost-ip-127-0-0-1-comment-author-instead-real/
I have not found a way to do that for Piwik.

**Comment by romaric33** [comment]
I'm back commenting on my own thread... Hope it can be of some use to someone because not being a developer, I am not very good at doing that kind of stuff.

Finally, turns out the issue is on Cloudways side: HTTP_X_FORWARDED_FOR returns both the visitor's IP and 127.0.0.1 for some reason. Module's front controller piwik.php has a private function, getVisitIp(), that is unable to handle that 2 IPs correctly.

**Original function**
`    private function getVisitIp() {
        $matchIp = '/^([0-9]{1,3}\.){3}[0-9]{1,3}$/';
        $ipKeys = array(
            'HTTP_X_FORWARDED_FOR',
            'HTTP_CLIENT_IP',
            'HTTP_CF_CONNECTING_IP',
        );
        foreach ($ipKeys as $ipKey) {
            if (isset($_SERVER[$ipKey]) && preg_match($matchIp, $_SERVER[$ipKey])) {
                return $_SERVER[$ipKey];
            }
        }
        return $this->arrayValue($_SERVER, 'REMOTE_ADDR');
    }`

For my own use I have replaced the getVisitIp() function with that code which is suitable for my environment and might be good for other Cloudways users. We take $_SERVER['HTTP_X_FORWARDED_FOR' provided by Cloudways server, then we explode so we can only use the first IP in it, which is the real one. Then we return its value in the same way it was done in the original function. 

**New function**
`    private function getVisitIp() {
        $xffaddrs = explode(',',$_SERVER['HTTP_X_FORWARDED_FOR']);
        $visitorrealip = $xffaddrs[0];
        return $visitorrealip;
        return $this->arrayValue($_SERVER, 'REMOTE_ADDR');
    }`

Now Piwik always gets the visitor's real IP and reports it well on the analytics dashboard.

**Comment by firstred** [comment]
Thanks! I have changed the function.

**Comment by firstred** [comment]
and slightly changed it so the other types may contain comma-separated values as well:
```php
protected function getVisitIp()
{
    $matchIp = '/^([0-9]{1,3}\.){3}[0-9]{1,3}$/';
    $ipKeys = [
        'HTTP_X_FORWARDED_FOR',
        'HTTP_CLIENT_IP',
        'HTTP_CF_CONNECTING_IP',
    ];
    foreach ($ipKeys as $ipKey) {
        if (isset($_SERVER[$ipKey]) && preg_match($matchIp, explode(',', $this->arrayValue($_SERVER, $ipKey))[0])) {
            return explode(',', $this->arrayValue($_SERVER, $ipKey))[0];
        }
    }

    return $this->arrayValue($_SERVER, 'REMOTE_ADDR');
}
```
